{
  "openapi": "3.0.1",
  "servers": [
    {
      "description": "API de Manutenção de Tabelas de Preço",
      "url": "{{host}}/api/hcg/v1"
    }
  ],
  "info": {
    "description": "API de Manutenção de Tabelas de Preço",
    "version": "1.000",
    "title": "Manutenção de Tabelas de Preço",
    "contact": {
      "name": "T-Talk",
      "url": "api.totvs.com.br",
      "email": "comiteintegracao@totvs.com.br"
    },
    "x-totvs": {
      "messageDocumentation": {
        "name": "ManutencaoTabelasPreco",
        "description": "Manutenção de Tabelas de Preço",
        "segment": "Construção e Projetos"
      },
      "productInformation": [
        {
          "product": "RM",
          "contact": "tribecp.squad.top.op@totvs.com.br",
          "description": "Manutenção de Tabelas de Preço",
          "adapter": "",
          "helpUrl": ""
        }
      ]
    }
  },
  "paths": {
    "/api/hcg/v1/maintenance-price-tables/procserv/copy": {
      "post": {
        "tags": [
          "procserv-copy"
        ],
        "summary": "Copia os registros de uma tabela de preço de Procedimentos e Serviços para outra",
        "description": "Copia os registros de uma tabela de preço de Procedimentos e Serviços para outra",
        "operationId": "procserv-copy",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": true,
              "note": "Este verbo esta disponivel com todos parametros",
              "minimalVersion": "12.1.2406"
            }
          ]
        },
        "requestBody": {
          "description": "Objeto para inserir um registro",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "CompanyId": {
                    "type": "integer",
                    "description": "Código da Coligada"
                  },
                  "OriginTableCode": {
                    "type": "string",
                    "description": "Código da tabela de preço origem"
                  },
                  "Filter": {
                    "type": "object",
                    "description": "Filtros utilizados para identificar as tabelas de preço a serem manipuladas"
                  },
                  "Filter.FilterType": {
                    "type": "string",
                    "description": "Tipo de filtro",
                    "enum": [
                      {
                        "T": "Total",
                        "E": "Especialidade",
                        "G": "Grupo",
                        "F": "Faixa"
                      }
                    ]
                  },
                  "Filter.SpecialtyCode": {
                    "type": "string",
                    "description": "Código da especialidade"
                  },
                  "Filter.ItensGroupCode": {
                    "type": "string",
                    "description": "Código do grupo de itens"
                  },
                  "Filter.StartRangeCode": {
                    "type": "string",
                    "description": "Código da faixa inicial"
                  },
                  "Filter.EndRangeCode": {
                    "type": "string",
                    "description": "Código da faixa final"
                  },
                  "ValueType": {
                    "type": "string",
                    "description": "Tipo de cópia de tabelas de preço",
                    "enum": [
                      {
                        "P": "Preservar",
                        "C": "Criar"
                      }
                    ]
                  },
                  "DestinyTableCode": {
                    "type": "string",
                    "description": "Código da tabela de preço destino"
                  },
                  "OverwriteDestinyTable": {
                    "type": "boolean",
                    "description": "Se deve sobrescrever os itens da tabela de preço destino, caso a mesma não esteja vazia"
                  }
                },
                "example": {
                  "CompanyId": 1,
                  "OriginTableCode": "01",
                  "Filter": {
                    "FilterType": "T",
                    "SpecialtyCode": "01",
                    "ItensGroupCode": "02",
                    "StartRangeCode": "01010001",
                    "EndRangeCode": "09099999"
                  },
                  "ValueType": "P",
                  "DestinyTableCode": "01",
                  "OverwriteDestinyTable": true
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Registro inserido com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response200"
                }
              }
            }
          },
          "406": {
            "description": "Erro no momento da inserção",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response406"
                }
              }
            }
          },
          "500": {
            "description": "Erro no momento da inserção",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response500"
                }
              }
            }
          }
        }
      }
    },
    "/api/hcg/v1/maintenance-price-tables/procserv/delete": {
      "post": {
        "tags": [
          "procserv-delete"
        ],
        "summary": "Exclui os registros de uma tabela de preço de Procedimentos e Serviços",
        "description": "Exclui os registros de uma tabela de preço de Procedimentos e Serviços",
        "operationId": "procserv-delete",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": true,
              "note": "Este verbo esta disponivel com todos parametros",
              "minimalVersion": "12.1.2406"
            }
          ]
        },
        "requestBody": {
          "description": "Objeto para deletar um registro",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "CompanyId": {
                    "type": "integer",
                    "description": "Código da Coligada"
                  },
                  "OriginTableCode": {
                    "type": "string",
                    "description": "Código da tabela de preço origem"
                  },
                  "Filter": {
                    "type": "object",
                    "description": "Filtros utilizados para identificar as tabelas de preço a serem manipuladas"
                  },
                  "Filter.FilterType": {
                    "type": "string",
                    "description": "Tipo de filtro",
                    "enum": [
                      {
                        "T": "Total",
                        "E": "Especialidade",
                        "G": "Grupo",
                        "F": "Faixa"
                      }
                    ]
                  },
                  "Filter.SpecialtyCode": {
                    "type": "string",
                    "description": "Código da especialidade"
                  },
                  "Filter.ItensGroupCode": {
                    "type": "string",
                    "description": "Código do grupo de itens"
                  },
                  "Filter.StartRangeCode": {
                    "type": "string",
                    "description": "Código da faixa inicial"
                  },
                  "Filter.EndRangeCode": {
                    "type": "string",
                    "description": "Código da faixa final"
                  }
                },
                "example": {
                  "CompanyId": 1,
                  "OriginTableCode": "01",
                  "Filter": {
                    "FilterType": "T",
                    "SpecialtyCode": "01",
                    "ItensGroupCode": "02",
                    "StartRangeCode": "01010001",
                    "EndRangeCode": "09099999"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Registro excluído com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response200"
                }
              }
            }
          },
          "406": {
            "description": "Erro no momento da exclusão",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response406"
                }
              }
            }
          },
          "500": {
            "description": "Erro no momento da exclusão",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response500"
                }
              }
            }
          }
        }
      }
    },
    "/api/hcg/v1/maintenance-price-tables/procserv/readjust": {
      "post": {
        "tags": [
          "procserv-readjust"
        ],
        "summary": "Reajusta os registros de uma tabela de preço de Procedimentos e Serviços",
        "description": "Reajusta os registros de uma tabela de preço de Procedimentos e Serviços",
        "operationId": "procserv-readjust",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": true,
              "note": "Este verbo esta disponivel com todos parametros",
              "minimalVersion": "12.1.2406"
            }
          ]
        },
        "requestBody": {
          "description": "Objeto para reajustar um registro",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "CompanyId": {
                    "type": "integer",
                    "description": "Código da Coligada"
                  },
                  "OriginTableCode": {
                    "type": "string",
                    "description": "Código da tabela de preço origem"
                  },
                  "Filter": {
                    "type": "object",
                    "description": "Filtros utilizados para identificar as tabelas de preço a serem manipuladas"
                  },
                  "Filter.FilterType": {
                    "type": "string",
                    "description": "Tipo de filtro",
                    "enum": [
                      {
                        "T": "Total",
                        "E": "Especialidade",
                        "G": "Grupo",
                        "F": "Faixa"
                      }
                    ]
                  },
                  "Filter.SpecialtyCode": {
                    "type": "string",
                    "description": "Código da especialidade"
                  },
                  "Filter.ItensGroupCode": {
                    "type": "string",
                    "description": "Código do grupo de itens"
                  },
                  "Filter.StartRangeCode": {
                    "type": "string",
                    "description": "Código da faixa inicial"
                  },
                  "Filter.EndRangeCode": {
                    "type": "string",
                    "description": "Código da faixa final"
                  },
                  "ConversionFactor": {
                    "type": "number",
                    "description": "Fator do reajuste (%)"
                  }
                },
                "example": {
                  "CompanyId": 1,
                  "OriginTableCode": "01",
                  "Filter": {
                    "FilterType": "T",
                    "SpecialtyCode": "01",
                    "ItensGroupCode": "02",
                    "StartRangeCode": "01010001",
                    "EndRangeCode": "09099999"
                  },
                  "ConversionFactor": 1.5
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Registro reajustado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response200"
                }
              }
            }
          },
          "406": {
            "description": "Erro no momento do reajuste",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response406"
                }
              }
            }
          },
          "500": {
            "description": "Erro no momento do reajuste",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response500"
                }
              }
            }
          }
        }
      }
    },
    "/api/hcg/v1/maintenance-price-tables/matmed/copy": {
      "post": {
        "tags": [
          "matmed-copy"
        ],
        "summary": "Copia os registros de uma tabela de preço de Materiais e Medicamentos para outra",
        "description": "Copia os registros de uma tabela de preço de Materiais e Medicamentos para outra",
        "operationId": "matmed-copy",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": true,
              "note": "Este verbo esta disponivel com todos parametros",
              "minimalVersion": "12.1.2406"
            }
          ]
        },
        "requestBody": {
          "description": "Objeto para inserir um registro",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "CompanyId": {
                    "type": "integer",
                    "description": "Código da Coligada"
                  },
                  "OriginTableCode": {
                    "type": "string",
                    "description": "Código da tabela de preço origem"
                  },
                  "Filter": {
                    "type": "object",
                    "description": "Filtros utilizados para identificar as tabelas de preço a serem manipuladas"
                  },
                  "Filter.FilterType": {
                    "type": "string",
                    "description": "Tipo de filtro",
                    "enum": [
                      {
                        "T": "Total",
                        "F": "Faixa"
                      }
                    ]
                  },
                  "Filter.StartRangeCode": {
                    "type": "string",
                    "description": "Código da faixa inicial"
                  },
                  "Filter.EndRangeCode": {
                    "type": "string",
                    "description": "Código da faixa final"
                  },
                  "ValueType": {
                    "type": "string",
                    "description": "Tipo de cópia de tabelas de preço",
                    "enum": [
                      {
                        "P": "Preservar",
                        "C": "Criar"
                      }
                    ]
                  },
                  "DestinyTableCode": {
                    "type": "string",
                    "description": "Código da tabela de preço destino"
                  },
                  "OverwriteDestinyTable": {
                    "type": "boolean",
                    "description": "Se deve sobrescrever os itens da tabela de preço destino, caso a mesma não esteja vazia"
                  }
                },
                "example": {
                  "CompanyId": 1,
                  "OriginTableCode": "01",
                  "Filter": {
                    "FilterType": "T",
                    "StartRangeCode": "01010001",
                    "EndRangeCode": "09099999"
                  },
                  "ValueType": "P",
                  "DestinyTableCode": "01",
                  "OverwriteDestinyTable": true
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Registro inserido com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response200"
                }
              }
            }
          },
          "406": {
            "description": "Erro no momento da inserção",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response406"
                }
              }
            }
          },
          "500": {
            "description": "Erro no momento da inserção",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response500"
                }
              }
            }
          }
        }
      }
    },
    "/api/hcg/v1/maintenance-price-tables/matmed/delete": {
      "post": {
        "tags": [
          "matmed-delete"
        ],
        "summary": "Exclui os registros de uma tabela de preço de Materiais e Medicamentos",
        "description": "Exclui os registros de uma tabela de preço de Materiais e Medicamentos",
        "operationId": "matmed-delete",
        "x-totvs": {
          "productInformation": [
            {
              "product": "RM",
              "available": true,
              "note": "Este verbo esta disponivel com todos parametros",
              "minimalVersion": "12.1.2406"
            }
          ]
        },
        "requestBody": {
          "description": "Objeto para deletar um registro",
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "CompanyId": {
                    "type": "integer",
                    "description": "Código da Coligada"
                  },
                  "OriginTableCode": {
                    "type": "string",
                    "description": "Código da tabela de preço origem"
                  },
                  "Filter": {
                    "type": "object",
                    "description": "Filtros utilizados para identificar as tabelas de preço a serem manipuladas"
                  },
                  "Filter.FilterType": {
                    "type": "string",
                    "description": "Tipo de filtro",
                    "enum": [
                      {
                        "T": "Total",
                        "F": "Faixa"
                      }
                    ]
                  },
                  "Filter.StartRangeCode": {
                    "type": "string",
                    "description": "Código da faixa inicial"
                  },
                  "Filter.EndRangeCode": {
                    "type": "string",
                    "description": "Código da faixa final"
                  }
                },
                "example": {
                  "CompanyId": 1,
                  "OriginTableCode": "01",
                  "Filter": {
                    "FilterType": "T",
                    "StartRangeCode": "01010001",
                    "EndRangeCode": "09099999"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Registro excluído com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response200"
                }
              }
            }
          },
          "406": {
            "description": "Erro no momento da exclusão",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response406"
                }
              }
            }
          },
          "500": {
            "description": "Erro no momento da exclusão",
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "https://raw.githubusercontent.com/totvs/ttalk-standard-message/master/jsonschema/schemas/MaintenancePriceTables_v1_000.json#/definitions/response500"
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {
    "schemas": {
    }
  }
}